### PR TITLE
prepare for a x64 build

### PR DESCRIPTION
**Pull request by chcg**
- prepare sln\vcxproj files for a x64 build
- needs followup PR which corrects the x64 var usage

### CODE REVIEW

**Comment by dail8859** [comment]
Thanks for the PR.

> needs followup PR which corrects the x64 var usage

You mean the additional warnings about conversions between types? 

One other thing I noticed was a few warnings I did not expect to see:

```
3>LexLPeg.obj : warning LNK4197: export 'GetLexerCount' specified multiple times; using first specification
3>LexLPeg.obj : warning LNK4197: export 'GetLexerName' specified multiple times; using first specification
3>LexLPeg.obj : warning LNK4197: export 'GetLexerFactory' specified multiple times; using first specification
```

I'm not sure what is causing this yet. Do you have any idea?

**Comment by chcg** [comment]
See e.g. http://www.scintilla.org/ScintillaDoc.html#SCI_GETDIRECTFUNCTION and http://www.scintilla.org/ScintillaDoc.html#SCI_GETDIRECTPOINTER

For x64 these are:
SciFnDirect pSciMsg = (SciFnDirect)SendMessage(hSciWnd, SCI_GETDIRECTFUNCTION, 0, 0);
sptr_t pSciWndData = (sptr_t)SendMessage(hSciWnd, SCI_GETDIRECTPOINTER, 0, 0);

and not just int as the documentation:

SCI_GETDIRECTFUNCTION → int
SCI_GETDIRECTPOINTER → int

makes one think.

warning LNK4197 seems to be caused by doubled export:
- via LexLPeg.def file in vcxproj
<ModuleDefinitionFile>$(SolutionDir)ext\scintillua\LexLPeg.def</ModuleDefinitionFile>
- and in code via 
#define EXT_LEXER_DECL __declspec( dllexport ) __stdcall

, see also https://msdn.microsoft.com/en-US/library/a90k134d.aspx  which states:

-  __declspec(dllexport) adds the export directive to the object file so you do not need to use a .def file.
, and also:
- However, using __declspec(dllexport) in addition to using a .def file does not cause build errors.

**Comment by chcg** [comment]
The necessary changes for usability with x64 would be:

```
 src/ScintillaGateway.h | 14 +++++++-------
 1 file changed, 7 insertions(+), 7 deletions(-)

diff --git a/src/ScintillaGateway.h b/src/ScintillaGateway.h
index c2b4803..220814a 100644
--- a/src/ScintillaGateway.h
+++ b/src/ScintillaGateway.h
@@ -44,9 +44,9 @@ public:
 	}
 
 	template<typename T, typename U>
-	inline int Call(unsigned int message, T wParam = 0, U lParam = 0) const {
+	inline sptr_t Call(unsigned int message, T wParam = 0, U lParam = 0) const {
 		sptr_t retVal = directFunction(directPointer, message, (uptr_t)wParam, (sptr_t)lParam);
-		return (int)retVal;
+		return retVal;
 	}
 
 	/* ++Autogenerated -- start of section automatically generated from Scintilla.iface */
@@ -1100,13 +1100,13 @@ public:
 		return res;
 	}
 
-	int GetDirectFunction() const {
-		int res = Call(SCI_GETDIRECTFUNCTION, SCI_UNUSED, SCI_UNUSED);
+	sptr_t GetDirectFunction() const {
+		sptr_t res = Call(SCI_GETDIRECTFUNCTION, SCI_UNUSED, SCI_UNUSED);
 		return res;
 	}
 
-	int GetDirectPointer() const {
-		int res = Call(SCI_GETDIRECTPOINTER, SCI_UNUSED, SCI_UNUSED);
+	sptr_t GetDirectPointer() const {
+		sptr_t res = Call(SCI_GETDIRECTPOINTER, SCI_UNUSED, SCI_UNUSED);
 		return res;
 	}
 
@@ -2950,7 +2950,7 @@ public:
 		return res;
 	}
 
-	int PrivateLexerCall(int operation, int pointer) const {
+	int PrivateLexerCall(int operation, LPARAM pointer) const {
 		int res = Call(SCI_PRIVATELEXERCALL, operation, pointer);
 		return res;
 	}
```
, but as ScintillaGateway.h is generated this needs to be corrected in the input file I think.

Further changes:

```
 src/Main.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/Main.cpp b/src/Main.cpp
index 661c10e..82fcfa4 100644
--- a/src/Main.cpp
+++ b/src/Main.cpp
@@ -81,7 +81,7 @@ static void SetLexer(const ScintillaGateway &editor, const std::string &language
 
 	editor.PrivateLexerCall(SCI_GETDIRECTFUNCTION, editor.GetDirectFunction());
 	editor.PrivateLexerCall(SCI_SETDOCPOINTER, editor.GetDirectPointer());
-	editor.PrivateLexerCall(SCI_SETLEXERLANGUAGE, reinterpret_cast<int>(language.c_str()));
+	editor.PrivateLexerCall(SCI_SETLEXERLANGUAGE, reinterpret_cast<LPARAM>(language.c_str()));
 
 	// Always show the folding margin. Since N++ doesn't recognize the file it won't have the margin showing.
 	editor.SetMarginWidthN(2, 14);
```


 ```
ext/scintillua/LexLPeg.cxx | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/ext/scintillua/LexLPeg.cxx b/ext/scintillua/LexLPeg.cxx
index 4bb4221..5a1c258 100644
--- a/ext/scintillua/LexLPeg.cxx
+++ b/ext/scintillua/LexLPeg.cxx
@@ -495,7 +495,7 @@ class LexerLPeg : public ILexer {
 	 * @param str The string to copy.
 	 * @return number of bytes needed to hold *str*
 	 */
-	void *StringResult(long lparam, const char *str) {
+	void *StringResult(sptr_t lparam, const char *str) {
 		if (lparam) strcpy(reinterpret_cast<char *>(lparam), str);
 		return reinterpret_cast<void *>(strlen(str));
 	}
@@ -606,13 +606,13 @@ public:
 			if (lua_pcall(L, 3, 1, 0) != LUA_OK) l_error(L);
 			// Style the text from the token table returned.
 			if (lua_istable(L, -1)) {
-				int len = lua_rawlen(L, -1);
+				size_t len = lua_rawlen(L, -1);
 				if (len > 0) {
 					styler.StartAt(startPos);
 					styler.StartSegment(startPos);
 					l_getlexerfield(L, "_TOKENSTYLES");
 					// Loop through token-position pairs.
-					for (int i = 1; i < len; i += 2) {
+					for (int i = 1; i < static_cast<int>(len); i += 2) {
 						style = STYLE_DEFAULT;
 						lua_rawgeti(L, -2, i), lua_rawget(L, -2); // _TOKENSTYLES[token]
 						if (!lua_isnil(L, -1)) style = lua_tointeger(L, -1);


```

**Comment by dail8859** [comment]
> warning LNK4197 seems to be caused by doubled export:

Then why wouldn't the 32 bit build give these same warnings? I've found the def file is required for the external lexer to export the correctly named functions. Without using the def file:

```
>dumpbin.exe /EXPORTS LexLPeg.dll
Microsoft (R) COFF/PE Dumper Version 12.00.40629.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file LexLPeg.dll

File Type: DLL

  Section contains the following exports for LexLPeg.dll

    00000000 characteristics
    58D04FB6 time date stamp Mon Mar 20 17:55:02 2017
        0.00 version
           1 ordinal base
           3 number of functions
           3 number of names

    ordinal hint RVA      name

          1    0 0006C355 _GetLexerCount@0 = @ILT+9040(_GetLexerCount@0)
          2    1 0006A84D _GetLexerFactory@4 = @ILT+2120(_GetLexerFactory@4)
          3    2 0006BCAC _GetLexerName@12 = @ILT+7335(_GetLexerName@12)

  Summary

        5000 .data
        1000 .idata
       25000 .rdata
        8000 .reloc
        1000 .rsrc
       DC000 .text
       69000 .textbss

```

 With the def the exported function names are different:

```
>dumpbin.exe /EXPORTS Lex
LPeg.dll
Microsoft (R) COFF/PE Dumper Version 12.00.40629.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file LexLPeg.dll

File Type: DLL

  Section contains the following exports for LexLPeg.dll

    00000000 characteristics
    58D051A6 time date stamp Mon Mar 20 18:03:18 2017
        0.00 version
           1 ordinal base
           3 number of functions
           3 number of names

    ordinal hint RVA      name

          1    0 0006C355 GetLexerCount = @ILT+9040(_GetLexerCount@0)
          2    1 0006A84D GetLexerFactory = @ILT+2120(_GetLexerFactory@4)
          3    2 0006BCAC GetLexerName = @ILT+7335(_GetLexerName@12)

  Summary

        5000 .data
        1000 .idata
       25000 .rdata
        8000 .reloc
        1000 .rsrc
       DC000 .text
       69000 .textbss
```

I'm not sure why Scintilla requires this but this is necessary.

---
> The necessary changes for usaability with x64 would be

Is this just suppress warnings or fix some bug?

**Comment by chcg** [comment]
1. changed decoration is due to __stdcall, see https://msdn.microsoft.com/en-us/library/56h2zst2.aspx#Format%20of%20a%20C%20decorated%20name

- __stdcall	Leading underscore (_) and a trailing at sign (@) followed by the number of bytes in the parameter list in decimal

and also there:

- Note that in a 64-bit environment, functions are not decorated.

Which probalby causes the naming collision between __declspec(dllexport) and def file just for x64 and not for x86.

2. x64 behaviour without the change from int -> sptr_t leads to a pointer truncation via the call interface and access on the other side (see https://github.com/dail8859/ScintilluaPlusPlu00s/blob/master/ext/scintillua/LexLPeg.cxx#L728 for the expansion back to a pointer) with the truncated pointer leads to a memory access error.

**Comment by dail8859** [comment]
Thanks for this info! It has been very helpful.

Can you also push an additional commit to this PR with the proposed changes to the 3 files you mentioned above? That way I can review it all together.

Thanks again!

**Comment by chcg** [comment]
OK.

Should I change the vcxproj file for win32 build back to the behaviour to build the interface with the .def file to avoid the decorated names?

**Comment by dail8859** [comment]
Yes please do.

**Comment by chcg** [comment]
- amended commit regarding usage of def file for win32
- added x64 adaptations, currently that causes compiler warnings on cast from sptr_t to int on each method containing call and return value is int in ScintillaGateway.h , like e.g. GetFontQuality():

```
int GetFontQuality() const {
		int res = Call(SCI_GETFONTQUALITY, SCI_UNUSED, SCI_UNUSED);
		return res;
}
```

**Comment by dail8859** [comment]
Thanks for the update. A couple comments:

1. Even with using `_CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES` I still get a few `warning C4996: 'strcpy'` from `lexlpeg.cxx`. Not a big deal to me just not sure why it isn't working. 
2. As for the additional warnings what would you recommend? Doing something like this?
```cpp
int GetFontQuality() const {
    sptr_t res = Call(SCI_GETFONTQUALITY, SCI_UNUSED, SCI_UNUSED);
    return static_cast<int>(res);
}
```

**Comment by chcg** [comment]
ad 1,
See https://msdn.microsoft.com/en-US/library/ms175759(v=vs.140).aspx

> Note that these template overloads only work for static arrays. Dynamically allocated buffers require additional source code changes. Revisiting the above examples:

```
#define _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES 1

...

char *szBuf = (char*)malloc(10);

strcpy(szBuf, "test"); // still deprecated; have to change to

// strcpy_s(szBuf, 10, "test");
```
, so the additional define doesn't fix the dynamic usecases seen in LexLPeg.cxx. VS2017 seems to no longer complain about it.
Should I remove  _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES?

ad 2,
Seems ok to me. How is the ScintillaGateway file generated? This might have some influence, as scintilla 3.7.4 is available and probably you don't want to break the behaviour or manually rework with every version upgrade of scintilla component.

**Comment by dail8859** [comment]
> Note that these template overloads only work for static arrays.

Ah should have seen that myself. :) Thanks.

> How is the ScintillaGateway file generated?

I have a python script (somewhere) that I use which reads Scintilla's "iface" file to generate that header file. As you pointed out some of the messages such as `SCI_GETDIRECTFUNCTION` are documented as returning `int` but I think adding a bit extra logic to it to do as you've done is a wise idea. Then anything that needs to can just `static_cast<>()` to the appropriate type.

**Comment by dail8859** [comment]
I've pushed a few more commits to this PR which should make this "ready enough" to merge if it looks good to you.

**Comment by chcg** [comment]
Looks fine to me, apart from the conflict.

Do you have\know a testset of input for the various lexer possibilities? This might make sense to test with such a set to see if no bug with x64 is hidden somewhere and no regression is introduced for the current x86 functionality.

**Comment by dail8859** [comment]
Thanks for looking over it. I'll handle the conflict and merge this soon.

**Comment by dail8859** [comment]
> Do you have\know a testset of input for the various lexer possibilities?

Nothing beyond very limited manual testing of opening up a couple of various files and visually glancing at them.

**Comment by dail8859** [comment]
Merged. Thanks again for the PR!

**Pull request merged**
